import { Helmet } from 'react-helmet-async';
import { motion } from 'framer-motion';
import { FileSignature } from 'lucide-react';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background py-16 px-4">
      <Helmet>
        <title>Terms of Service – AgroSmart</title>
        <meta name="description" content="Terms of service for AgroSmart platform." />
      </Helmet>

      <div className="max-w-4xl mx-auto mt-8">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-card border border-border rounded-3xl p-8 md:p-12 shadow-sm"
        >
          <div className="flex items-center gap-4 mb-8 pb-8 border-b border-border">
            <div className="w-14 h-14 bg-green-500/10 rounded-2xl flex items-center justify-center">
              <FileSignature className="w-7 h-7 text-green-500" />
            </div>
            <div>
              <h1 className="text-3xl font-bold text-foreground mb-1">Terms of Service</h1>
              <p className="text-muted-foreground">Effective Date: May 21, 2026</p>
            </div>
          </div>

          <div className="prose prose-emerald dark:prose-invert max-w-none text-muted-foreground">
            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">1. Agreement to Terms</h2>
            <p className="mb-4 leading-relaxed">
              These Terms of Service constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("you") and AgroSmart ("we," "us" or "our"), concerning your access to and use of the AgroSmart website and platform. You agree that by accessing the site, you have read, understood, and agree to be bound by all of these Terms of Service.
            </p>

            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">2. User Representations</h2>
            <p className="mb-4 leading-relaxed">
              By using the Site, you represent and warrant that:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>All registration information you submit will be true, accurate, current, and complete.</li>
              <li>You will maintain the accuracy of such information and promptly update such registration information as necessary.</li>
              <li>You have the legal capacity and you agree to comply with these Terms of Service.</li>
              <li>You will not use the Site for any illegal or unauthorized purpose.</li>
            </ul>

            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">3. Prohibited Activities</h2>
            <p className="mb-4 leading-relaxed">
              You may not access or use the Site for any purpose other than that for which we make the Site available. The Site may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us. Prohibited activities include, but are not limited to:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>Systematically retrieving data or other content from the Site to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.</li>
              <li>Tricking, defrauding, or misleading us and other users, especially in any attempt to learn sensitive account information such as user passwords.</li>
              <li>Interfering with, disrupting, or creating an undue burden on the Site or the networks or services connected to the Site.</li>
            </ul>

            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">4. Platform and API Usage</h2>
            <p className="mb-4 leading-relaxed">
              AgroSmart provides tools for monitoring and managing farm data via IoT devices and APIs. You are responsible for ensuring that the devices connecting to our platform are secure and comply with local regulations. We reserve the right to throttle or block API access if we detect abnormal usage patterns that threaten platform stability.
            </p>

            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">5. Disclaimer</h2>
            <p className="mb-4 leading-relaxed bg-background p-6 rounded-2xl border border-border mt-6 italic">
              The Site is provided on an as-is and as-available basis. You agree that your use of the Site and our services will be at your sole risk. To the fullest extent permitted by law, we disclaim all warranties, express or implied, in connection with the site and your use thereof. We make no warranties or representations about the accuracy or completeness of the site's content or the data generated by the platform.
            </p>

            <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">6. Changes to Terms</h2>
            <p className="mb-4 leading-relaxed">
              We reserve the right, in our sole discretion, to make changes or modifications to these Terms of Service at any time and for any reason. We will alert you about any changes by updating the "Effective Date" of these Terms of Service, and you waive any right to receive specific notice of each such change.
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
